name: pulsar_iot_client
description: Apache Pulsar IoT client
homepage: https://github.com/activeobd/pulsar_iot_client
version: 1.0.3

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  logging: ^1.0.2
  protobuf: ^2.0.1
  crclib: ^3.0.0
  tuple: ^2.0.0
  fixnum: ^1.0.0
  convert: ^3.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  oauth2: ^2.0.0

